### ISSUE TITLE
Context Length Option With File Context Enabled Doesn't Limit Length

### ISSUE THREAD

**Issue by anaseinea** [rjmacarthy/twinny#253] opened 2024-05-24 20:03 UTC
**Describe the bug**
Context Length Option With File Context Enabled Doesn't Limit Length of FIM sent

**To Reproduce**
Enable File Context option and set Context Length then use FIM and check number of lines sent

**API Provider**
 Ollama

**Chat or Auto Complete?**
FIM

**Comment by rjmacarthy** [comment] 2024-05-27 19:56
Hey thanks, this is a duplicate of https://github.com/rjmacarthy/twinny/issues/23 which is basically a task to adhere to LLM context window.  We need to know the context window size and tokeniser for each LLM being used it is not a trivial task and the context enabled feature is pretty much experimental.

**Closed by rjmacarthy** 2024-05-27 19:56 UTC
