### ISSUE TITLE
Not working with localforward to remote ollama server

### ISSUE THREAD

**Issue by eriktar** [rjmacarthy/twinny#93] opened 2024-02-06 09:55 UTC
In my setup I have a underpowered laptop where I do my coding and a beefy server to handle ollama.  The server is not on the internet, and needs to be accessed via a jump host on ssh.  I use `LocalForward 11434 10.10.0.233:11434` to emulate having it locally.  

For curl and other vscode plugins like Continue it appears that my ollama server is available on localhost
```
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "codellama:13b",
  "prompt": "Write me a function that outputs the fibonacci sequence"
}'

{"model":"codellama:13b","created_at":"2024-02-06T07:24:29.612339609Z","response":"\t","done":false}
{"model":"codellama:13b","created_at":"2024-02-06T07:24:29.635149631Z","response":"if","done":false}
{"model":"codellama:13b","created_at":"2024-02-06T07:24:29.657876752Z","response":" err","done":false}
{"model":"codellama:13b","created_at":"2024-02-06T07:24:29.680659605Z","response":" :=","done":false}
{"model":"codellama:13b","created_at":"2024-02-06T07:24:29.703439665Z","response":" validate","done":false}
...
```

Twinny however does not appear to be compatible with this setup, and keeps insisting I should install ollama locally.
<img width="460" alt="image" src="https://github.com/rjmacarthy/twinny/assets/5344481/77962b37-ef43-4451-8d45-7645a62cf153">

**Expected behavior**
Since the configuration is all about ports and urls, I'm expecting Twinny to try and use the `port:host` combo I set up, not any other systemcalls to ollama.

**Desktop**
<img width="244" alt="image" src="https://github.com/rjmacarthy/twinny/assets/5344481/5be89b94-c113-4f8e-abb1-72c6e6b9369b">
<img width="236" alt="image" src="https://github.com/rjmacarthy/twinny/assets/5344481/35815700-f8eb-4863-b24f-5abf1aaa5b10">

**Comment by rjmacarthy** [comment] 2024-02-06 12:09
Hey thanks for the info, this seems to be a Duplicate of https://github.com/rjmacarthy/twinny/issues/70?

**Comment by eriktar** [comment] 2024-02-06 15:31
Yup.  Thats a duplicate.  Did not spot since the summary/title was windows.

**Closed** 2024-02-06 16:02 UTC
Labels: duplicate
