### ISSUE TITLE
using oobabooga text generation webui instead of ollama

### ISSUE THREAD

**Issue by LitenBuzzTh** [rjmacarthy/twinny#72] opened 2024-02-03 14:32 UTC
Hi
thanks for your awesome efforts on this!
As you might know, oobabooga text generation webui also offers openAI like api through one of its extensions, and being able to utilize that using twinny, would be a game changer.

anybody had any success doing so?

**Comment by jakern** [comment] 2024-02-04 01:14
I haven't tried it but it seems pretty straight forward changing the ports and the api endpoint. The twinny settings page has notes in the description for configuring llama.cpp. I bet that will work for you if your text-gen-ui has the api enabled

**Comment by rjmacarthy** [comment] 2024-02-05 11:42
I think it would require some work to edit the payload which is sent to the oobabooga API so I don't think just updating the API settings will work.

**Comment by jakern** [comment] 2024-02-05 17:17
I must be confusing the llama.cpp model backend with what is exposed through the api. I'm looking forward to trying it out myself.

**Comment by rjmacarthy** [comment] 2024-02-08 12:56
Hey, it appears that LM Studio and oobabooga and many other APIs support similar data structures to OpenAI API I am in the middle of implementing support for LM Studio so hopefully using this preset will also work for oobabooga api too.  I did not test it because I did not install oobabooga api yet.

https://github.com/rjmacarthy/twinny/pull/98

**Comment by kha84** [comment] 2024-02-08 20:33
Haven't tried the above code from #98 merge request, but still running this version of Twinny in VSCode 1.86.0:

![image](https://github.com/rjmacarthy/twinny/assets/110789576/fffd1206-3158-437d-9b41-427bfad13d02)

I injected some simple logging to oobabooga:

```
$ git diff
diff --git a/modules/text_generation.py b/modules/text_generation.py
index 1917a0c1..d05c988a 100644
--- a/modules/text_generation.py
+++ b/modules/text_generation.py
@@ -443,5 +443,7 @@ def generate_reply_custom(question, original_question, seed, state, stopping_str
         t1 = time.time()
         original_tokens = len(encode(original_question)[0])
         new_tokens = len(encode(original_question + reply)[0]) - original_tokens
+        print(f'Question: {question}')
+        print(f'Reply: {reply}')
         print(f'Output generated in {(t1-t0):.2f} seconds ({new_tokens/(t1-t0):.2f} tokens/s, {new_tokens} tokens, context {original_tokens}, seed {seed})')
         return
```

... and now I can see ooba is perfectly accepting completion requests and responding back, when Twinny is configured like this:

Api Url: ip or hostname
Fim Api Port: 5000
Chat Fim Path: /v1/completions

....but for some reason Twinny doesn't paste the model' response back to editor. 
I have a wild guess it just takes the wrong piece from JSON, while still thinking it's ollama-like. 

Would be great to have any kind of debugging console for Twinny to troubleshoot that.

**Comment by rjmacarthy** [comment] 2024-02-09 14:09
Please could you update to the latest version and try again?

**Comment by kha84** [comment] 2024-02-09 20:37
Nah, still the same, unfortunately.
In oobabooga logs (with my extra piece) I see this:
```
Llama.generate: prefix-match hit

llama_print_timings:        load time =     169.27 ms
llama_print_timings:      sample time =       0.11 ms /    16 runs   (    0.01 ms per token, 149532.71 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =     436.53 ms /    16 runs   (   27.28 ms per token,    36.65 tokens per second)
llama_print_timings:       total time =     452.12 ms /    17 tokens
Question: <｜fim▁begin｜>

# Language: Python (python)
# File uri: untitled:Untitled-2 (python)
import pyspark

# add two numbers
<｜fim▁hole｜><｜fim▁end｜>
Reply: num1 = 1.5
num2 = 6.3

Output generated in 0.76 seconds (23.81 tokens/s, 18 tokens, context 81, seed 55953560)
```
But Twinny doesn't show this suggestion.
I also enabled the logging setting:
```
"twinny.enableLogging": true
```
but nothing is getting printed to "Output" or to "Debug console".

**Comment by kha84** [comment] 2024-02-09 22:04
I made a curl request manually just to be sure:
```
curl -XPOST http://oobaboogahost:5000/v1/completions  \
-H "Authorization: Bearer mypassword" \
-H "Content-Type: application/json"   -d '{
    "prompt": "<｜fim▁begin｜> def main(<｜fim▁hole｜> <｜fim▁end｜>",
    "max_tokens": 5,
    "temperature": 0.5,
    "top_p": 0.9,
    "seed": 10
  }'
```
And it replied with this JSON:
```
{
    "id": "conv-1707516141850207744",
    "object": "text_completion",
    "created": 1707516141,
    "model": "deepseek-coder-33b-base.Q4_K_M.gguf",
    "choices": [
        {
            "index": 0,
            "finish_reason": "length",
            "text": "):\n    print(",
            "logprobs": {
                "top_logprobs": [
                    {}
                ]
            }
        }
    ],
    "usage": {
        "prompt_tokens": 28,
        "completion_tokens": 6,
        "total_tokens": 34
    }
}
```
I guess Twinny should be taking the reply from choices[0]["text"]

**Comment by rjmacarthy** [comment] 2024-02-09 22:17
It should if you use LM studio as your API provider.

https://github.com/rjmacarthy/twinny/blob/d69c03098dcdebf7893cc92d0fa021625b1334f4/src/requests.ts#L76

**Comment by kha84** [comment] 2024-02-09 23:58
It might be the case there's something wrong with ooba. Will test the latest version out with Jan.AI and llama.cpp tomorrow and report you back. They both should provide the same OpenAI compatible API REST endpoints

**Comment by rjmacarthy** [comment] 2024-02-10 08:57
It could be something in the code that I am doing incorrectly. I will check it next week by installing ooba API. Maybe the streaming data is different but the API request is the same. 

Many thanks,

**Comment by kha84** [comment] 2024-02-10 12:56
Would be great. 

Today I checked Twinny against [Jan.AI](https://jan.ai/) installed locally. Jan.AI is truly opensource inference desktop app, supporting Linux, Max and Windows. A drop-in replacement of proprietary LM Studio. As I said before, Jan.AI is having the built-in OpenAI-compatible API, but running on a slightly different endpoint (`/v1/chat/completions`) compared to llama.cpp built-in webserver or LM Studio.  So first, I've made a simple curl call to ensure Jan works fine and able to respond:

```
curl -XPOST http://localhost:1337/v1/chat/completions  -H "Content-Type: application/json"   -d '{
    "prompt": "<｜fim▁begin｜> def main(<｜fim▁hole｜> <｜fim▁end｜>",
    "max_tokens": 50,
    "temperature": 0.1,
    "top_p": 0.9,
    "seed": 10,
    "model":"deepseek-coder-1.3b"
  }'
```
And it did respond me with this JSON:
```
{
    "choices": [
      {
        "finish_reason": null,
        "index": 0,
        "message": {
          "content": "\nThe code you provided is a simple Python script that uses the `requests` library to send HTTP requests. However, it doesn't seem like there are any errors in your code or logic here as you haven\u2019t provided the specifics of",
          "role": "assistant"
        }
      }
    ],
    "created": 1707566932,
    "id": "qC6duduhv0pq80xhnoTv",
    "model": "_",
    "object": "chat.completion",
    "system_fingerprint": "_",
    "usage": {
      "completion_tokens": 50,
      "prompt_tokens": 4,
      "total_tokens": 54
    }
  }
```
Then I tried to configure Twinny to use it:
* "llama.cpp" or "lmstudio" as an API provider
* port was 1337 (as I used in curl) for both chat and fim (fill-in-the-middle)
* API path was set to "/v1/chat/completions" for both - this is what I have seen working for manual curl requests
... but none of that worked. I can see in Jan.AI logs, it is responding with 404, as if wrong API path was requested or something was missing in JSON request, but unfortunately currently Jan logs are not very verbose to see further details. I've raised feature request for that - https://github.com/janhq/jan/issues/1989

Would be great if Twinny could have some debug on it's own side to see what it is sending out and what kind of responses it gets back from server backends. There's a debug checkbox in settings, but it looks like it doesn't do much at this point.

**Comment by rjmacarthy** [comment] 2024-02-10 13:56
If you enable twinny debug settings and open dev tools for vscode you should see some information on latest version of twinny.

**Comment by kha84** [comment] 2024-02-10 14:09
Thanks a lot! It helped. The single bit is missing, when we talk about Jan.AI OpenAI implementation is "model" thing. The requests that are being sent by Twinny right now looks like this:
```
{
  "prompt": "<｜fim▁begin｜>\none and one is <｜fim▁hole｜><｜fim▁end｜>",
  "stream": true,
  "max_tokens": -1,
  "temperature": 0.2
}
```
whereas Jan.AI expects to see one more field - "model". E.g. they should look like this:
```
{
  "prompt": "<｜fim▁begin｜>\none and one is <｜fim▁hole｜><｜fim▁end｜>",
  "stream": true,
  "max_tokens": -1,
  "temperature": 0.2,
  "model":"deepseek-coder-1.3b"
}
```

**Comment by rjmacarthy** [comment] 2024-02-10 20:05
I just added `model` to the request in version `3.5.14` let me know if it helps.

Many thanks,

**Comment by kha84** [comment] 2024-02-10 21:26
I can see the improvement! It did help - Jan is no longer responding back with 404, but Twinny still doesn't show the autocompletion. 

I think there might be an issue with `"stream": true` in JSON. 
There's a noticable difference if I mage curl calls with strem set to true or false.
Here's with stream set to true (this is what Twinny does right now):
```
$ curl -XPOST http://localhost:1337/v1/chat/completions  -H "Content-Type: application/json"   -d '{
  "model": "deepseek-coder-1.3b",
  "prompt": "<｜fim▁begin｜>\none and one is <｜fim▁hole｜><｜fim▁end｜>",
  "stream": true,
  "max_tokens": -1,
  "temperature": 0.2
}'
data: {"choices":[{"delta":{"content":"\n"},"finish_reason":null,"index":0}],"created":1707600176,"id":"TaGsr7QQGfBBCWz8TDSj","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"The"},"finish_reason":null,"index":0}],"created":1707600176,"id":"Knz6vYJ3M15CjbstrUGu","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" code"},"finish_reason":null,"index":0}],"created":1707600176,"id":"p9gu6aVOkmnxGXvBPagT","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" sn"},"finish_reason":null,"index":0}],"created":1707600176,"id":"0pm5Ickntj7ngYMXmvUR","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"ip"},"finish_reason":null,"index":0}],"created":1707600176,"id":"F3GbL4J6MGK6ttMSBLAh","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"pet"},"finish_reason":null,"index":0}],"created":1707600176,"id":"I6b0N3Wdgh3aTUB6BJFi","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" you"},"finish_reason":null,"index":0}],"created":1707600176,"id":"1NQtPlYh0ANkJMstrhdV","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" provided"},"finish_reason":null,"index":0}],"created":1707600177,"id":"29Xb3dDoDkjKxYFckwqn","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" is"},"finish_reason":null,"index":0}],"created":1707600177,"id":"RbdsN2jGBMv3Cq5CYiqI","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" a"},"finish_reason":null,"index":0}],"created":1707600177,"id":"HZB5hBnpyKD05rAb7umU","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" Python"},"finish_reason":null,"index":0}],"created":1707600177,"id":"ug8dQwckOeoIuWHCPRIb","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" script"},"finish_reason":null,"index":0}],"created":1707600177,"id":"DUlxE3j4wDmIUCPUN0Ft","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" that"},"finish_reason":null,"index":0}],"created":1707600177,"id":"y0obmk2hmA3IXg3IFgah","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" uses"},"finish_reason":null,"index":0}],"created":1707600177,"id":"GvnBY5AUkJrceTGUs2a6","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" the"},"finish_reason":null,"index":0}],"created":1707600177,"id":"uXKPcSBaYg0NIj76LTKi","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" Py"},"finish_reason":null,"index":0}],"created":1707600177,"id":"ex7PIVIUMMQFEVzDgPag","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"Tor"},"finish_reason":null,"index":0}],"created":1707600178,"id":"kRIo3bZw1ZxW7gxjvsdH","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"ch"},"finish_reason":null,"index":0}],"created":1707600178,"id":"5e0DkLvRRVYaGWIcsyIr","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" library"},"finish_reason":null,"index":0}],"created":1707600178,"id":"U3cnJ5oNbbCi5gheXb2C","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" to"},"finish_reason":null,"index":0}],"created":1707600178,"id":"fXtmxS0RjCyTpNoQ5gCP","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" train"},"finish_reason":null,"index":0}],"created":1707600178,"id":"X9wxKT9gayQ23Gf8AAE0","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" an"},"finish_reason":null,"index":0}],"created":1707600178,"id":"QsvDQbBoCEuSUfkDJDqb","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" L"},"finish_reason":null,"index":0}],"created":1707600178,"id":"9glvKFgG0qQzzMV8nTTO","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"STM"},"finish_reason":null,"index":0}],"created":1707600178,"id":"1sMetoLUjgEQCy4UbDh5","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" model"},"finish_reason":null,"index":0}],"created":1707600178,"id":"6nMJ0aAZFXq3hMgCY0FR","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" on"},"finish_reason":null,"index":0}],"created":1707600179,"id":"8tpuXWnGiq7T4Zs6j2bA","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" some"},"finish_reason":null,"index":0}],"created":1707600179,"id":"ppnfP8b4JcmA8QQbmd4d","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" data"},"finish_reason":null,"index":0}],"created":1707600179,"id":"YecpQOcA4dNXXxVxK5tl","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"."},"finish_reason":null,"index":0}],"created":1707600179,"id":"PNEDwb9hp6wEAEXFJ3yr","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" The"},"finish_reason":null,"index":0}],"created":1707600179,"id":"Rdpo8BZrqGNdVDhkZtvS","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" training"},"finish_reason":null,"index":0}],"created":1707600179,"id":"J18Pjr98BLC1xbnmpSzK","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" process"},"finish_reason":null,"index":0}],"created":1707600179,"id":"u3V1CehDX2ABfsCxGXQM","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" involves"},"finish_reason":null,"index":0}],"created":1707600179,"id":"IxrzNqLwEbMayXaCfx6a","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" feeding"},"finish_reason":null,"index":0}],"created":1707600179,"id":"wrAvWPtxLSYWFsMicFis","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" in"},"finish_reason":null,"index":0}],"created":1707600180,"id":"EE60y1ssws6YyycfBW9r","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" bat"},"finish_reason":null,"index":0}],"created":1707600180,"id":"ip5aGJhNcECiccV4m0uI","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"ches"},"finish_reason":null,"index":0}],"created":1707600180,"id":"VXtnrszzNs4vxs0ZVKuQ","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" of"},"finish_reason":null,"index":0}],"created":1707600180,"id":"z9PgWPioLcjGLUof6uq9","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" input"},"finish_reason":null,"index":0}],"created":1707600180,"id":"gJQD18oWz1j4EYFUbC95","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" and"},"finish_reason":null,"index":0}],"created":1707600180,"id":"SHAt0nNTDDQMLK080BHr","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" output"},"finish_reason":null,"index":0}],"created":1707600180,"id":"w68JD92WTJqMiJEimTj6","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" pairs"},"finish_reason":null,"index":0}],"created":1707600180,"id":"FhslqlpepWy7TwXuQs4U","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":","},"finish_reason":null,"index":0}],"created":1707600180,"id":"Gn6reJYtSr3PoiOJ4woW","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" updating"},"finish_reason":null,"index":0}],"created":1707600181,"id":"7bm8Z0U5hxlUes8u35Hg","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" weights"},"finish_reason":null,"index":0}],"created":1707600181,"id":"CsO3VabxzyNgbahOfg9a","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" based"},"finish_reason":null,"index":0}],"created":1707600181,"id":"mTwVyXTPAXv2TJtArfI0","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" on"},"finish_reason":null,"index":0}],"created":1707600181,"id":"WBhICOjBMDFWUs4OsL4z","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" the"},"finish_reason":null,"index":0}],"created":1707600181,"id":"UvlBCWWfN9Y2s0JGXEFt","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" grad"},"finish_reason":null,"index":0}],"created":1707600181,"id":"jgu1F6orrGC7RBlu1t7a","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"ients"},"finish_reason":null,"index":0}],"created":1707600181,"id":"kKHfOyfje4EoGn0lHFAe","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" computed"},"finish_reason":null,"index":0}],"created":1707600181,"id":"hvhIbol96USTYaQNQxj8","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" during"},"finish_reason":null,"index":0}],"created":1707600181,"id":"xpsVS1Bvw0gZnD0v5td4","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" back"},"finish_reason":null,"index":0}],"created":1707600181,"id":"FKXbnPCowgOZG3VZvoEA","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"prop"},"finish_reason":null,"index":0}],"created":1707600182,"id":"64geYARLcAkJA36pmhF3","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"ag"},"finish_reason":null,"index":0}],"created":1707600182,"id":"bREvx2FdTtlOVNQw23Qq","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"ation"},"finish_reason":null,"index":0}],"created":1707600182,"id":"v97z8kToth1CwjFvf4v0","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" ("},"finish_reason":null,"index":0}],"created":1707600182,"id":"3NNqhoSiI3aP5luGRYG2","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"which"},"finish_reason":null,"index":0}],"created":1707600182,"id":"OwQMhcxdgYMFpYrlICmR","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" is"},"finish_reason":null,"index":0}],"created":1707600182,"id":"keBTwC8TccPe30j79K9D","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" what"},"finish_reason":null,"index":0}],"created":1707600182,"id":"i4E5py9kUd8ET4JLL9vE","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" happens"},"finish_reason":null,"index":0}],"created":1707600182,"id":"fDgeLqmaPXtUPJ26jhnZ","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" when"},"finish_reason":null,"index":0}],"created":1707600182,"id":"weB52Maspc8w925kLV98","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" you"},"finish_reason":null,"index":0}],"created":1707600182,"id":"Ov8vHI1UMS1wSuvLBcN0","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" run"},"finish_reason":null,"index":0}],"created":1707600183,"id":"EGBPFOHcBzsdswxcETMz","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" your"},"finish_reason":null,"index":0}],"created":1707600183,"id":"sGm9eq0gV5HziY2WnqGf","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" training"},"finish_reason":null,"index":0}],"created":1707600183,"id":"zJt7z9jXFGlrIdny252S","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" loop"},"finish_reason":null,"index":0}],"created":1707600183,"id":"2GY1ik5jYW0Coa5NJ2Jv","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"),"},"finish_reason":null,"index":0}],"created":1707600183,"id":"cJ3GnHDk1nQsvp5vHT5H","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" then"},"finish_reason":null,"index":0}],"created":1707600183,"id":"hs8ZnH6iS0fOINTnv2kP","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" repeating"},"finish_reason":null,"index":0}],"created":1707600183,"id":"JUpHNKFvPdhprk61NK5O","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" this"},"finish_reason":null,"index":0}],"created":1707600183,"id":"T2FXCI8IGTWFyRiBHzU0","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" process"},"finish_reason":null,"index":0}],"created":1707600184,"id":"X0378w1ojDwZa0lg2Loh","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" for"},"finish_reason":null,"index":0}],"created":1707600184,"id":"EBF8tmycmkYf2MD7LQSP","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" a"},"finish_reason":null,"index":0}],"created":1707600184,"id":"wBPicy1IQWjz9ebe2KkN","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" number"},"finish_reason":null,"index":0}],"created":1707600184,"id":"7xDQhTSgtgl6tQVe9eIH","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" of"},"finish_reason":null,"index":0}],"created":1707600184,"id":"TcwJdDPj1BqaHzMar7eK","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" epoch"},"finish_reason":null,"index":0}],"created":1707600184,"id":"59HhZMM4hpIhAAzVPAnZ","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"s"},"finish_reason":null,"index":0}],"created":1707600185,"id":"6nZOmFfZs2SzyKM0ln28","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"."},"finish_reason":null,"index":0}],"created":1707600185,"id":"UVOG6PaEoJeCt3Ah1q0D","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"\n"},"finish_reason":null,"index":0}],"created":1707600185,"id":"LmzaHJ4eYOMmIy8V3kYk","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":""},"finish_reason":null,"index":0}],"created":1707600185,"id":"Vx04HeYGKDpSPx7Y9gPH","model":"_","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":""},"finish_reason":"stop","index":0}],"created":1707600185,"id":"SBMl01ID9I0gWqZ2cSVr","model":"_","object":"chat.completion.chunk"}

data: [DONE]
```

And here's with stream set to false:
```
$ curl -XPOST http://localhost:1337/v1/chat/completions  -H "Content-Type: application/json"   -d '{
  "model": "deepseek-coder-1.3b",
  "prompt": "<｜fim▁begin｜>\none and one is <｜fim▁hole｜><｜fim▁end｜>",
  "stream": false,
  "max_tokens": -1,
  "temperature": 0.2
}'
{"choices":[{"finish_reason":null,"index":0,"message":{"content":"\nThe code you provided is a simple Python script that uses the `requests` library to send HTTP requests. However, it's missing some crucial parts such as headers and URL parameters which are necessary for making a request successful in the context of this script:\n```python \nimport requests   # Importing Requests library to send HTTP Request.   \nurl = \"http://example.com\"     // URL of the website you want to access   # Replace with your target url \nresponse=requests.get(url)    // Sending a GET request and storing the response in 'Response'   # Replace with your target url \nprint (response.text )        // Printing out text of webpage content from the server response   \n```   # Replace with your target url \nPlease note that this script is a simple example and doesn't handle any potential errors or exceptions. You should add error handling code to make your scripts more robust, for instance by catching specific types of exception that might be raised when making requests and dealing with responses.\n","role":"assistant"}}],"created":1707600269,"id":"iIHO1uIerkh5SOlWt9ce","model":"_","object":"chat.completion","system_fingerprint":"_","usage":{"completion_tokens":224,"prompt_tokens":4,"total_tokens":228}}
```




Does Twinny actually support streamed response and knows how to interpret it?
Here's the screenshot from developer console:
![image](https://github.com/rjmacarthy/twinny/assets/110789576/63303cfe-c971-49cc-9c1e-cea56bd52ef6)
I think, if you change that stream from true to false it should do the job.

**Comment by rjmacarthy** [comment] 2024-02-10 23:05
Hey, please try a base model e.g https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-base it should work.

**Comment by kha84** [comment] 2024-02-11 09:49
I can confirm that code autocompletion in version 3.5.14 is working with oobabooga as a backend now! 
That is awesome, thanks a lot. 
Here are the plugin settings I used, just in case if others will be interested:

```
Api Hostname            : ip_address_of_your_oobabooga_installation 
Api provider            : lmstudio 
Chat Api Path           : /v1/chat/completions 
Chat Api Port           : 5000 
Fim Api Port            : 5000 
Fim Api Path            : /v1/completions 
Chat Model Name         : for oobabooga it does not matter, as model is loaded on oobabooga side 
Fim Model Name          : for oobabooga it does not matter, as model is loaded on oobabooga side 
Fim Template Format     : deepseek  (just because I use deepseek-coder-xx-base model in Ooba)
Disable Auto Suggest    : true  (this is my personal preference. Do not like to overload server with extra requests, 
                          I prefer manual autocompletion triggered by  Alt + \)
Use File Context        : false 
Enable Completion Cache : false 
Num Predict Chat        : 512 
Num Predict Fim         : -1 
Disable Server Checks   : true  (disabled it in order to prevent plugin asking me all the time to install ollama)
Api Bearer Token        : mysecuredpassword  (if you have set an api password in oobabooga 
                          with --api --api-key mysecuredpassword)
```

The only thing I noticed is that chat on the left-hand side doesn't work - most probably chat templates should be tuned for deepseek base model. In Oobabooga, chats the very same model work fine. But that's an easy part, I think one should able to play with it and fix this by himself, based on the chosen model.

Will check the same for Jan.AI as a backend bit later again.

**Comment by kha84** [comment] 2024-02-11 10:15
So the fix for chat was easy one, if anyone is using the deepseek models, just change the contents of system.hbs to this value:
```
The following is a conversation with an AI Large Language Model. The AI has been trained to answer questions, provide recommendations, and help with decision making. The AI follows user requests. The AI thinks outside the box.

```

**Comment by rjmacarthy** [comment] 2024-02-11 13:53
Awesome, thanks!

**Comment by rjmacarthy** [comment] 2024-02-11 20:19
Oobabooga API is now supported 🍾

**Closed by rjmacarthy** 2024-02-11 20:19 UTC
